name: Push

on: 
  push: 
    branches: main

jobs: 
  Push:
    runs-on: ubuntu-latest 
    steps: 
      - name: Login to harbor
        uses: docker/login-action@v3 
        with: 
          registry: harbor.alfredbrowniii.io 
          username: ${{ vars.HARBOR_USERNAME }}
          password: ${{ secrets.HABOR_PASSWORD }}
          