name: Push

on: 
  push: 
    branches: main

jobs: 
  Push:
    runs-on: ubuntu-latest 
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Login to harbor
        env:
          USERNAME: ${{ vars.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.HABOR_PASSWORD }}
        uses: docker/login-action@v3 
        with: 
          registry: https://harbor.alfredbrowniii.io 
          username: robot$github
          password: byvHUpRytc6jWZ2qswqfoFTqUnvNvshJ
      # - name: Setup Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      - name: Build and Push
        uses: docker/build-push-action@v6  
        with: 
          push: true
          tags: harbor.alfredbrowniii.io:443/docker/rbac-controller:latest


